version: '3.4'

networks:
  todo-app-demo-net:

services:
  redis:
    image: "redis:alpine"
    networks:
      - todo-app-demo-net

  server:
    build: ./server
    networks:
      - todo-app-demo-net
    ports:
     - "8000:8000"

  app:
    build: ./app
    ports:
      - "3000:3000"

  